apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-kv-k3s-rpi
spec:

  # # Used to select the correct ESO controller (think: ingress.ingressClassName)
  # # The ESO controller is instantiated with a specific controller name
  # # and filters ES based on this property
  # # Optional
  # controller: dev

  # You can specify retry settings for the http connection
  # these fields allow you to set a maxRetries before failure, and
  # an interval between the retries.
  # Current supported providers: AWS, IBM
  retrySettings:
    maxRetries: 5
    retryInterval: "10s"

  # provider field contains the configuration to access the provider
  # which contains the secret exactly one provider must be configured.
  provider:

    vault:
      server: "https://vault.vault:8200"
      # Path is the mount path of the Vault KV backend endpoint
      path: "kv-k3s-rpi"
      version: "v2"
      caProvider:
        type: "ConfigMap"
        name: "kube-root-ca.crt"
        key: "ca.crt"
        namespace: {{ .Release.Namespace }}
      auth:


        # Kubernetes auth: https://www.vaultproject.io/docs/auth/kubernetes
        kubernetes:
          mountPath: "kubernetes"
          role: "es-k8s-oidc-access"
          # Optional service account reference
          serviceAccountRef:
            name: "vault-external-secrets"
