apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-oidc-access
spec:

  # Optional, SecretStoreRef defines the default SecretStore to use when fetching the secret data.
  secretStoreRef:
    name: vault-kv-k3s-rpi
    kind: SecretStore  # or ClusterSecretStore

  refreshInterval: "1h"

  target:
    deletionPolicy: "Delete"

    # Specify a blueprint for the resulting Kind=Secret
    template:
      type: Opaque

  # Used to fetch all properties from the Provider key
  # If multiple dataFrom are specified, secrets are merged in the specified order
  dataFrom:
  - extract:
      key: k8s-oidc-access
      # version: latest
      # property: data
      conversionStrategy: Default
